### ISSUE TITLE
Last merge request doesn't added to release notes. 

### ISSUE THREAD

**Issue by Jasstkn** [jk1z/gitlab-release-note-generator#8]
Hi! I'm testing your tool and I've noticed something strange - the last merged merge request didn't appear in release notes. Here my gitlab-ci.yaml
```
stages:
  - deploy
  - post_deploy

tag-after-deployment:
  only:
    refs:
      - master
      - develop
  except:
    refs:
      - tags
  stage: deploy
  image: debian:stable
  before_script:
    - source environments/lab/make.env
    - apt-get clean -qq
    - apt-get update -qq --fix-missing
    - apt-get install -qq --fix-missing jq git
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan git-stage.nordigy.ru >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - export VERSION=$DOCKER_TAG
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config -l
    - git remote set-url origin "git@git-stage.nordigy.ru:contact-center/integrations/devops/environments/engage-digital.git"
    - git remote -v
  script:
    - git tag -af "${VERSION}" ${CI_COMMIT_SHA} -m "${VERSION}"
    - git push origin --tags -f

generate-release-note:
  only:
    refs:
      - tags
  stage: post_deploy
  image: docker:18-git
  services:
    - docker:18-dind
  script:
    - docker container run -e GITLAB_PERSONAL_TOKEN=${GITLAB_ACCESS_TOKEN} -e GITLAB_API_ENDPOINT="https://git-stage.nordigy.ru/api/v4" -e GITLAB_PROJECT_ID=${CI_PROJECT_ID} 00freezy00/gitlab-release-note-generator
```

I compared commits SHA and they are the same in pipeline and in tag.

**Comment by jk1z** [comment]
Can I get the logs that are outputted by the app, please?
 
Also, Is your merged request in `closed` state? And Is it closed in between 2 of your tags?

**Comment by jk1z** [comment]
Another possible reason why your latest merge request is not in the release note is that you didn't specify the TARGET_TAG_REGEX in the app docker env. The generator could be finding the merge requests `updated at` time in between a develop tag and a master tag.

**Comment by jk1z** [comment]
The way I set up the release note generator for develop and master branch is something like this

```
# for master branch
generate-release-note:
    allow_failure: true
    only:
        refs:
            - tags
        variables:
            - $CI_COMMIT_TITLE =~ /^[0-9]+.[0-9]+.[0-9]+$/
    stage: post_deploy
    image: docker:stable
    services:
        - docker:dind
    script:
        - docker container run -e GITLAB_PERSONAL_TOKEN=${GITLAB_PERSONAL_TOKEN} -e GITLAB_PROJECT_ID=${CI_PROJECT_ID} -e TARGET_TAG_REGEX="^v[0-9]+.[0-9]+.[0-9]+$" 00freezy00/gitlab-release-note-generator

# for develop branch
generate-release-note:
    allow_failure: true
    only:
        refs:
            - tags
        variables:
            - $CI_COMMIT_TITLE =~ /^[0-9]+.[0-9]+.[0-9]+(-[0-9]+)$/
    stage: post_deploy
    image: docker:stable
    services:
        - docker:dind
    script:
        - docker container run -e GITLAB_PERSONAL_TOKEN=${GITLAB_PERSONAL_TOKEN} -e GITLAB_PROJECT_ID=${CI_PROJECT_ID} -e TARGET_TAG_REGEX="^v[0-9]+.[0-9]+.[0-9]+(-[0-9]+)$" 00freezy00/gitlab-release-note-generator
```
Note It's **impossible** to distinguish the release tag by which branch they belong to in a develop and a master branch setup. Because your develop branch will eventually get merged into the master for a production release and that makes the `tag` belongs to both develop and master branch.

The better way of doing it is using Regex to distinguish the tag whether it's on master or develop branch.
